blueprint:
  name: IKEA Rodret Dimmer Controls patched
  description: >
    ## Control anything with IKEA RODRET Dimmer remote (ZHA only)

    Only for use with [ZHA](https://www.home-assistant.io/integrations/zha/).

    Available controls:

    - Press the **on** or **off** buttons
    - Double press the **on** or **off** buttons (optional) in **Helper - Double press delay** interval.
      When disabled, there will be no delay for the simple press actions.
    - Press and hold the **on**/**off** buttons. Actions will be executed every **Helper - Hold delay**,
      but maximum **Helper - Max number of loops** times.

  source_url: https://gist.github.com/damru/b2c1c780ffb0ddc084952eb89db9573a
  domain: automation

  input:
    remote_device:
      name: (ZHA) Remote
      description: IKEA RODRET Dimmer remote to use. **Only ZHA is supported in this version.**
      default: ""
      selector:
        device:
          filter:
            integration: zha
            manufacturer: IKEA of Sweden
            model: RODRET Dimmer
          multiple: false

    on_press_action:
      name: On - Single press action
      description: Choose action(s) to run when **on** button is pressed.
      default: []
      selector:
        action: {}

    off_press_action:
      name: Off - Single press action
      description: Choose action(s) to run when **off** button is **pressed**.
      default: []
      selector:
        action: {}

    on_hold_action:
      name: On - Hold action
      description: Choose action(s) to run when **on** button is **pressed and held**.
      default: []
      selector:
        action: {}

    off_hold_action:
      name: Off - Hold action
      description: Choose action(s) to run when **off** button is **pressed and held**.
      default: []
      selector:
        action: {}

    on_double_press:
      name: On - Double press event
      description: >
        Enable if you want a separate action for **on** button double press.
        When disabled, **on** single press will fire immediately without delay.
      default: false
      selector:
        boolean: {}

    on_double_press_action:
      name: On - Double press action
      description: >
        Action(s) to run when pressing the **on** button twice within **Helper - Double press
        delay**.
      default: []
      selector:
        action: {}

    off_double_press:
      name: Off - Double press event
      description: >
        Enable if you want a separate action for **off** button double press.
        When disabled, **off** single press will fire immediately without delay.
      default: false
      selector:
        boolean: {}

    off_double_press_action:
      name: Off - Double press action
      description: >
        Action(s) to run when pressing the **off** button twice within **Helper - Double press
        delay**.
      default: []
      selector:
        action: {}

    helper_double_press_delay:
      name: Helper - Double press delay
      description: >
        Max delay between the first and the second button press for the
        **Double press events**. Increase this value if you notice that the double
        press action is not triggered reliably.
      default: 250
      selector:
        number:
          unit_of_measurement: milliseconds
          min: 100.0
          max: 5000.0
          step: 10.0
          mode: slider

    helper_hold_delay:
      name: Helper - Hold delay
      description: Delay between each execution of the **Hold** action(s).
      default: 250
      selector:
        number:
          unit_of_measurement: milliseconds
          min: 100.0
          max: 5000.0
          step: 10.0
          mode: slider

    helper_max_loops:
      name: Helper - Max number of loops
      description: Maximum number of loops when holding down a button.
      default: 20
      selector:
        number:
          min: 1.0
          max: 1000.0
          step: 1.0
          mode: slider

mode: restart
max_exceeded: silent

trigger_variables:
  zha_remote: !input remote_device

trigger:
  # ON press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: "{{ zha_remote }}"
      command: "on"
    id: press-on-zha

  # OFF press
  - platform: event
    event_type: zha_event
    event_data:
      device_id: "{{ zha_remote }}"
      command: "off"
    id: press-off-zha

  # ON hold (brightness up)
  - platform: event
    event_type: zha_event
    event_data:
      device_id: "{{ zha_remote }}"
      command: "move_with_on_off"
    id: hold-on-zha

  # OFF hold (brightness down)
  - platform: event
    event_type: zha_event
    event_data:
      device_id: "{{ zha_remote }}"
      command: "move"
    id: hold-off-zha

  # Release (stop move) – used only inside wait_for_trigger
  - platform: event
    event_type: zha_event
    event_data:
      device_id: "{{ zha_remote }}"
      command: "stop_with_on_off"
    id: release-zha

action:
  - variables:
      on_double_press: !input on_double_press
      off_double_press: !input off_double_press

  - choose:
      # --- ON button pressed ---
      - conditions:
          - condition: trigger
            id:
              - press-on-zha
        sequence:
          - if:
              - condition: template
                value_template: "{{ on_double_press }}"
            then:
              - wait_for_trigger:
                  - platform: event
                    event_type: zha_event
                    event_data:
                      device_id: "{{ zha_remote }}"
                      command: "on"
                timeout:
                  milliseconds: !input helper_double_press_delay
                continue_on_timeout: true
              - if:
                  - condition: template
                    value_template: "{{ wait.trigger is not none }}"
                then: !input on_double_press_action
                else: !input on_press_action
            else: !input on_press_action

      # --- OFF button pressed ---
      - conditions:
          - condition: trigger
            id:
              - press-off-zha
        sequence:
          - if:
              - condition: template
                value_template: "{{ off_double_press }}"
            then:
              - wait_for_trigger:
                  - platform: event
                    event_type: zha_event
                    event_data:
                      device_id: "{{ zha_remote }}"
                      command: "off"
                timeout:
                  milliseconds: !input helper_double_press_delay
                continue_on_timeout: true
              - if:
                  - condition: template
                    value_template: "{{ wait.trigger is not none }}"
                then: !input off_double_press_action
                else: !input off_press_action
            else: !input off_press_action

      # --- ON hold (brightness up) ---
      - conditions:
          - condition: trigger
            id:
              - hold-on-zha
        sequence:
          - repeat:
              count: !input helper_max_loops
              sequence:
                - parallel:
                    - sequence: !input on_hold_action
                    - sequence:
                        - wait_for_trigger:
                            - platform: event
                              event_type: zha_event
                              event_data:
                                device_id: "{{ zha_remote }}"
                                command: "stop_with_on_off"
                          timeout:
                            milliseconds: !input helper_hold_delay
                          continue_on_timeout: true
                        - if:
                            - condition: template
                              value_template: "{{ wait.trigger is not none }}"
                          then:
                            - stop: button released

      # --- OFF hold (brightness down) ---
      - conditions:
          - condition: trigger
            id:
              - hold-off-zha
        sequence:
          - repeat:
              count: !input helper_max_loops
              sequence:
                - parallel:
                    - sequence: !input off_hold_action
                    - sequence:
                        - wait_for_trigger:
                            - platform: event
                              event_type: zha_event
                              event_data:
                                device_id: "{{ zha_remote }}"
                                command: "stop_with_on_off"
                          timeout:
                            milliseconds: !input helper_hold_delay
                          continue_on_timeout: true
                        - if:
                            - condition: template
                              value_template: "{{ wait.trigger is not none }}"
                          then:
                            - stop: button released
