blueprint:
  name: ZHA - IKEA four button remote for lights patched
  description: >
    Control lights with an IKEA four button remote (the square ones),
    for use with ZHA.

    Extends SwerveShot's version which is based on the work of frenck
    with the five button version.

    Pressing the up button will turn on the lights at the last set brightness
    (unless the force brightness is toggled on in the blueprint).

    Pressing the down button will turn the lights off again.

    Pressing and holding the up/down buttons will change the brightness
    smoothly and can be pressed and held until the brightness is satisfactory.

    The "left" and "right" buttons can be assigned to a short and long
    button press action. Use the left and right button events with care, as
    before the long press event is sent, the "on" event gets triggered.

  domain: automation

  input:
    remote:
      name: Remote
      description: IKEA remote to use
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: Remote Control N2
          multiple: false

    light:
      name: Light(s)
      description: The light(s) to control
      selector:
        target:
          entity:
            - domain:
                - light

    force_brightness:
      name: Force turn on brightness
      description: >
        Force the brightness to the set level below, when the "on" button
        on the remote is pushed and lights turn on.
      default: false
      selector:
        boolean: {}

    brightness:
      name: Brightness
      description: Brightness of the light(s) when turning on
      default: 50
      selector:
        number:
          min: 0.0
          max: 100.0
          mode: slider
          step: 1.0
          unit_of_measurement: "%"

    hold_time:
      name: Hold Time
      description: >
        Time between the execution of the brighter/darker actions when
        holding the brighter/darker button.
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 2.0
          step: 0.1
          unit_of_measurement: seconds
          mode: slider

    button_left_short:
      name: Left button - short press
      description: Action to run on short left button press
      default: []
      selector:
        action: {}

    button_left_long:
      name: Left button - long press
      description: >
        Action to run on long left button press. Use with care, as before
        the long press event is sent, the "on" event gets triggered.
      default: []
      selector:
        action: {}

    button_right_short:
      name: Right button - short press
      description: Action to run on short right button press
      default: []
      selector:
        action: {}

    button_right_long:
      name: Right button - long press
      description: >
        Action to run on long right button press. Use with care, as before
        the long press event is sent, the "on" event gets triggered.
      default: []
      selector:
        action: {}

  source_url: https://community.home-assistant.io/t/zha-ikea-four-button-remote-styrbar-for-lights-e2001-e2002/384482

mode: restart
max_exceeded: silent

trigger_variables:
  remote_device: !input remote

variables:
  force_brightness: !input force_brightness
  target_light: !input light
  turn_on_brightness: !input brightness
  hold_time_var: !input hold_time
  remote_device: !input remote

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: "{{ remote_device }}"

action:
  - variables:
      command: "{{ trigger.event.data.command | default('') }}"
      cluster_id: "{{ trigger.event.data.cluster_id | int(0) }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id | int(0) }}"
      args: "{{ trigger.event.data.args | default([]) }}"

  - choose:
      # === ON (UP) button pressed ===
      - conditions:
          - "{{ command == 'on' }}"
          - "{{ cluster_id == 6 }}"
          - "{{ endpoint_id == 1 }}"
        sequence:
          - choose:
              - conditions:
                  - "{{ force_brightness }}"
                sequence:
                  - service: light.turn_on
                    target: "{{ target_light }}"
                    data:
                      transition: 1
                      brightness_pct: "{{ turn_on_brightness }}"
            default:
              - service: light.turn_on
                target: "{{ target_light }}"
                data:
                  transition: 1

      # === OFF (DOWN) button pressed ===
      - conditions:
          - "{{ command == 'off' }}"
          - "{{ cluster_id == 6 }}"
          - "{{ endpoint_id == 1 }}"
        sequence:
          - service: light.turn_off
            target: "{{ target_light }}"
            data:
              transition: 1

      # === UP hold: brighten while held ===
      - conditions:
          - "{{ command == 'move_with_on_off' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
        sequence:
          - repeat:
              # Safety cap: at most 50 steps per hold
              count: 50
              sequence:
                - parallel:
                    - service: light.turn_on
                      target: "{{ target_light }}"
                      data:
                        brightness_step_pct: 10
                        transition: "{{ hold_time_var }}"
                    - sequence:
                        - wait_for_trigger:
                            - platform: event
                              event_type: zha_event
                              event_data:
                                device_id: "{{ remote_device }}"
                                command: "stop"
                            - platform: event
                              event_type: zha_event
                              event_data:
                                device_id: "{{ remote_device }}"
                                command: "stop_with_on_off"
                          timeout:
                            seconds: "{{ hold_time_var }}"
                          continue_on_timeout: true
                        - if:
                            - condition: template
                              value_template: "{{ wait.trigger is not none }}"
                          then:
                            - stop: button released

      # === DOWN hold: dim while held ===
      - conditions:
          - "{{ command == 'move' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
        sequence:
          - repeat:
              # Safety cap: at most 50 steps per hold
              count: 50
              sequence:
                - parallel:
                    - service: light.turn_on
                      target: "{{ target_light }}"
                      data:
                        brightness_step_pct: -10
                        transition: "{{ hold_time_var }}"
                    - sequence:
                        - wait_for_trigger:
                            - platform: event
                              event_type: zha_event
                              event_data:
                                device_id: "{{ remote_device }}"
                                command: "stop"
                            - platform: event
                              event_type: zha_event
                              event_data:
                                device_id: "{{ remote_device }}"
                                command: "stop_with_on_off"
                          timeout:
                            seconds: "{{ hold_time_var }}"
                          continue_on_timeout: true
                        - if:
                            - condition: template
                              value_template: "{{ wait.trigger is not none }}"
                          then:
                            - stop: button released

      # === LEFT button: short press ===
      - conditions:
          - "{{ command == 'press' }}"
          - "{{ cluster_id == 5 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [257, 13, 0] }}"
        sequence: !input button_left_short

      # === LEFT button: long press ===
      - conditions:
          - "{{ command == 'hold' }}"
          - "{{ cluster_id == 5 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [3329, 0] }}"
        sequence: !input button_left_long

      # === RIGHT button: short press ===
      - conditions:
          - "{{ command == 'press' }}"
          - "{{ cluster_id == 5 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [256, 13, 0] }}"
        sequence: !input button_right_short

      # === RIGHT button: long press ===
      - conditions:
          - "{{ command == 'hold' }}"
          - "{{ cluster_id == 5 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [3328, 0] }}"
        sequence: !input button_right_long
